# I. Numpy

### Импортируйте NumPy

In [1]:
import numpy as np


### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [44]:
# создаем одномерный массив c 0
array = np.zeros(10)

# пятый элемент равный делаем 1
array[4]=1
print("task 1, одномерный массив из 0 и пятый элемент 1:")
print(array)

# делаем массив двумерным
array = array.reshape(2,5)
print("task 2, двумерный массив:")
print(array)


task 1, одномерный массив из 0 и пятый элемент 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
task 2, двумерный массив:
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [49]:
# создаем одномерный массив со значениями от 10 до 49
array = np.random.randint(10, 49, size=39)
print("task 1, одномерный массив, со значениями от 10 до 49: ")
print(array)

# разворачиваем массив
array_new = array[::-1]
print("task 2, развернутый:")
print(array_new)

# находим все четные элементы в развернутом массиве
even_elements = [element for element in array_new if element % 2 == 0]

# выводим результат
print("task 3, четные элементы массива:")
print(even_elements)


task 1, одномерный массив, со значениями от 10 до 49: 
[20 27 37 23 34 28 30 19 10 12 13 19 12 30 39 33 39 29 20 22 45 12 47 36
 45 16 47 36 15 20 32 13 11 29 22 33 11 20 25]
task 2, развернутый:
[25 20 11 33 22 29 11 13 32 20 15 36 47 16 45 36 47 12 45 22 20 29 39 33
 39 30 12 19 13 12 10 19 30 28 34 23 37 27 20]
task 3, четные элементы массива:
[20, 22, 32, 20, 36, 16, 36, 12, 22, 20, 30, 12, 12, 10, 30, 28, 34, 20]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [50]:
# Создание двумерного массива 3x3 со значениями от 0 до 8
array = np.arange(9).reshape(3, 3)
print("task 1, двумерный массив 3x3 со значениями от 0 до 8:")
print(array)


task 1, двумерный массив 3x3 со значениями от 0 до 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [64]:
# cоздаем массив 4x3x2 со случайными значениями от 0 до 100
random_array = np.random.randint(0, 101, size=(4, 3, 2))

# находим минимум и максимум в массиве
min_value = np.min(random_array)
max_value = np.max(random_array)

# выводим результаты
print("task 1, массив 4x3x2")
print(random_array)
print("task 2, Минимум:", min_value)
print("task 3, Максимум:", max_value)


task 1, массив 4x3x2
[[[70 63]
  [56  4]
  [70 45]]

 [[14 65]
  [52 14]
  [58 48]]

 [[15 93]
  [93 16]
  [66  7]]

 [[46  2]
  [24 34]
  [64 74]]]
task 2, Минимум: 2
task 3, Максимум: 93


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [65]:
# создание первого массива размером 6x4
array1 = np.random.randint(0, 101, size=(6, 4))

# создание второго массива размером 4x3
array2 = np.random.randint(0, 101, size=(4, 3))

# матричное умножение
product = np.matmul(array1, array2)

# вывод результатов
print("Первый массив:\n", array1)
print("Второй массив:\n", array2)
print("Произведение матриц:\n", product)


Первый массив:
 [[27 36 56 61]
 [ 5 15 37 55]
 [84 68 58 35]
 [48 95  1  8]
 [30 96 46 41]
 [22 55 54  5]]
Второй массив:
 [[91  1  0]
 [43  9 29]
 [85 50 24]
 [53 14 22]]
Произведение матриц:
 [[11998  4005  3730]
 [ 7160  2760  2533]
 [17353  4086  4134]
 [ 8962  1065  2955]
 [12941  3768  4790]
 [ 9222  3287  3001]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [81]:
# создаем случайный двумерный массив 7x7
array = np.random.randint(0, 101, size=(7, 7))

# находим среднее значение всех элементов массива
mean = array.mean()

# находим стандартное отклонение всех элементов массива
std_dev = array.std()

# нормализуем массив, разделив каждый элемент на стандартное отклонение и вычтя среднее
normalized_arr = (array - mean) / std_dev

# выводим результаты
print("Созданный  случайный массив:")
print(array)
print("Среднее значение:", mean)
print("Стандартное отклонение:", std_dev)
print("Нормализованный массив:")
print(normalized_arr)

Созданный  случайный массив:
[[47  2 39 35 94 97 15]
 [37 45 85 37 26  9 79]
 [85 80 94  8  6  5 13]
 [83 62 38 82  2 91 71]
 [15 74 98 70 41  3 93]
 [79 95 42 17 67  0  7]
 [ 6 57 62 39 90 89 64]]
Среднее значение: 50.51020408163265
Стандартное отклонение: 33.05908282304891
Нормализованный массив:
[[-0.10617972 -1.46737901 -0.3481707  -0.46916619  1.31551732  1.40626394
  -1.07414366]
 [-0.40866845 -0.16667746  1.04327746 -0.40866845 -0.74140605 -1.25563689
   0.86178422]
 [ 1.04327746  0.89203309  1.31551732 -1.28588577 -1.34638351 -1.37663239
  -1.1346414 ]
 [ 0.98277971  0.34755338 -0.37841958  0.95253084 -1.46737901  1.2247707
   0.61979324]
 [-1.07414366  0.71053986  1.43651281  0.58954436 -0.28767296 -1.43713013
   1.28526844]
 [ 0.86178422  1.34576619 -0.25742408 -1.01364591  0.49879774 -1.52787675
  -1.31613464]
 [-1.34638351  0.19630901  0.34755338 -0.3481707   1.19452182  1.16427295
   0.40805112]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

### Загрузите датасет Tips из набора датасетов seaborn

### Посмотрите на первые 5 строчек

### Узнайте сколько всего строчек и колонок в данных

### Проверьте есть ли пропуски в данных

### Посмотрите на распределение числовых признаков

### Найдите максимальное значение 'total_bill'

### Найдите количество курящих людей

### Узнайте какой средний 'total_bill' в зависимости от 'day'

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

### Постройте pairplot

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.